// Generated by CoffeeScript 1.9.0
(function() {
  var PubNub, createProxyServer, http, port, pubnub, server;

  http = require('http');

  createProxyServer = function(pubnub, logger) {
    if (logger == null) {
      logger = console;
    }
    return http.createServer(function(req, res) {
      var jsonString;
      if (req.method === 'POST') {
        jsonString = '';
        req.on('data', function(data) {
          return jsonString += data;
        });
        return req.on('end', function() {
          var message;
          message = JSON.parse(jsonString);
          pubnub.publish({
            channel: req.url.substr(1),
            message: message
          }).then(function() {
            return logger.log("POSTED " + message.action.type + ": " + (JSON.stringify(message, null, 2)));
          })["catch"](function(e) {
            return logger.error("FAILED to publish " + message.action.type, e);
          });
          res.writeHead(200, 'OK', {
            'Content-Type': 'text/plain'
          });
          return res.end();
        });
      } else if (req.method === 'HEAD') {
        logger.log("HEAD " + req.url);
        res.writeHead(200, {
          'Content-Type': 'text/plain'
        });
        return res.end();
      }
    });
  };

  module.exports = {
    createProxyServer: createProxyServer
  };

  if (require.main === module) {
    PubNub = require('pubnub');
    pubnub = new PubNub({
      ssl: true,
      publishKey: 'pub-c-0b20bfbc-2c49-4f20-82ac-659d8ebb490c',
      subscribeKey: 'sub-c-f3c0a50c-d79f-11e4-9532-0619f8945a4f',
      userId: 'trellomx-webhook-proxy'
    });
    port = process.env.port || 1337;
    server = createProxyServer(pubnub);
    server.listen(port, function() {
      return console.info("Trello2PubNub Proxy running on " + port);
    });
  }

}).call(this);
