// Generated by CoffeeScript 1.9.0
(function() {
  var http, port, pubnub;

  http = require('http');

  pubnub = require('pubnub')({
    ssl: true,
    publish_key: 'pub-c-0b20bfbc-2c49-4f20-82ac-659d8ebb490c',
    subscribe_key: 'sub-c-f3c0a50c-d79f-11e4-9532-0619f8945a4f'
  });

  port = process.env.port || 1337;

  console.info("Trello2PubNub Proxy running on " + port);

  http.createServer(function(req, res) {
    var jsonString;
    if (req.method === 'POST') {
      jsonString = '';
      req.on('data', function(data) {
        return jsonString += data;
      });
      return req.on('end', function(data) {
        var message;
        message = JSON.parse(jsonString);
        pubnub.publish({
          channel: req.url.substr(1),
          message: message,
          callback: function() {
            return console.log("POSTED " + message.action.type + ": " + (JSON.stringify(message, null, 2)));
          },
          error: function(e) {
            return console.error("FAILED to publish " + message.action.type, e);
          }
        });
        res.writeHead(200, 'OK', {
          'Content-Type': 'text/plain'
        });
        return res.end();
      });
    } else if (req.method === 'HEAD') {
      console.log("HEAD " + req.url);
      res.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      return res.end();
    }
  }).listen(port);

}).call(this);
